// <auto-generated />
using System;
using ExpressionEngine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpressionEngine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205175328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpressionEngine.Core.Models.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000001"),
                            Expression = "A + B",
                            Name = "Add",
                            OperationType = 0
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000002"),
                            Expression = "A - B",
                            Name = "Subtract",
                            OperationType = 0
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000003"),
                            Expression = "A * B",
                            Name = "Multiply",
                            OperationType = 0
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000004"),
                            Expression = "A / B",
                            Name = "Divide",
                            OperationType = 0
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000005"),
                            Expression = "A % B",
                            Name = "Modulo",
                            OperationType = 0
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000006"),
                            Expression = "min(A,B)",
                            Name = "Min",
                            OperationType = 0
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000007"),
                            Expression = "max(A,B)",
                            Name = "Max",
                            OperationType = 0
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000008"),
                            Expression = "A + B",
                            Name = "Concat",
                            OperationType = 1
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-000000000009"),
                            Expression = "A - B",
                            Name = "Remove",
                            OperationType = 1
                        },
                        new
                        {
                            Id = new Guid("0180b8c0-0000-7e01-8000-00000000000a"),
                            Expression = "A * B",
                            Name = "Repeat",
                            OperationType = 1
                        });
                });

            modelBuilder.Entity("ExpressionEngine.Core.Models.OperationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationHistories");
                });

            modelBuilder.Entity("ExpressionEngine.Core.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Operators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Name = "Add",
                            Symbol = "+"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Name = "Subtract",
                            Symbol = "-"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Name = "Multiply",
                            Symbol = "*"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Name = "Divide",
                            Symbol = "/"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Name = "Modulo",
                            Symbol = "%"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            Name = "Min",
                            Symbol = "min"
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            Name = "Max",
                            Symbol = "max"
                        });
                });

            modelBuilder.Entity("ExpressionEngine.Core.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Tokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Symbol = "A",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Symbol = "B",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Symbol = "+",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Symbol = "-",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Symbol = "*",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Symbol = "/",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Symbol = "%",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Symbol = "(",
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            Symbol = ")",
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            Symbol = "min",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Symbol = "max",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Symbol = ",",
                            Type = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
