@ExpressionEngine_HostAddress = https://localhost:7139

### Get operations
GET {{ExpressionEngine_HostAddress}}/api/operations
Accept: application/json

###

### Calculate
POST {{ExpressionEngine_HostAddress}}/api/calculate
Content-Type: application/json

{
  "operationId": "0180b8c0-0000-7e01-8000-000000000001",
  "valueA": "2",
  "valueB": "3"
}

###

### Create valid operation 1
POST {{ExpressionEngine_HostAddress}}/api/operations
Content-Type: application/json

{
  "name": "Test1",
  "expression": "A / (B - B)",
  "type": 0
}

### Create invalid operation 2
POST {{ExpressionEngine_HostAddress}}/api/operations
Content-Type: application/json

{
  "name": "Test2",
  "expression": "A ++ B",
  "type": 0
}

### Create invalid operation 3
POST {{ExpressionEngine_HostAddress}}/api/operations
Content-Type: application/json

{
  "name": "Test3",
  "expression": "(A + B",
  "type": 0
}

### Create invalid operation 4
POST {{ExpressionEngine_HostAddress}}/api/operations
Content-Type: application/json

{
  "name": "Test4",
  "expression": "A / B",
  "type": 1
}

### Create invalid operation 5
POST {{ExpressionEngine_HostAddress}}/api/operations
Content-Type: application/json

{
  "name": "Test5",
  "expression": "A ++ B",
  "type": 1
}

### Create invalid operation 6
POST {{ExpressionEngine_HostAddress}}/api/operations
Content-Type: application/json

{
  "name": "Test6",
  "expression": "min(A,B)",
  "type": 0
}

###

### Update valid operation 1
PUT {{ExpressionEngine_HostAddress}}/api/operations
Content-Type: application/json

{
  "operationId": "019c2f06-1fa5-7a57-8c73-b983058f9a9c",
  "expression": "A / (B - B)"
}

###

### Delete valid operation 1
DELETE {{ExpressionEngine_HostAddress}}/api/operations/019c2f06-1fa5-7a57-8c73-b983058f9a9c
